### ISSUE TITLE
Allow pre-allocated array of telemetry frames/node data *and* incremental stacking it at every node

### ISSUE THREAD

**Issue by brockners** [inband-oam/ietf#10]
Incremental extension of the packet (like done in P4 INT) is more friendly to hardware implementations, pre-allocated array is beneficial to software implementations (performance reasons: Packet extension requires ~30 extra cycles in e.g. VPP implementation).
Changes:

- Document both options in the draft (pre-allocated array and incremental array extension)
- State that a domain has to implement *either* of the approaches, but not both at the same time. This way a mixed HW / SW dataplane could implement incremental extension, whereas a software only deployment could benefit from a pure pre-allocated array implementation. At the same time complexities of a hybrid approach are avoided.
- For implementations which use incremental extension, the ingress node needs to “cheat” on PMTU discovery – i.e. taking the max. size that a packet can grow to into account.

**Comment by shwethab** [comment]
Added 2 trace options - one that is pre-allocated and another incremental.
The option headers are different but the node data format will be the same except for the incremental option allowing variable length field - opaque snapshot state.
https://github.com/inband-oam/ietf/commit/6e30056794221bc0207614b345916ad908024fc1
