### ISSUE TITLE
Wide and short timestamps

### ISSUE THREAD

**Issue by brockners** [inband-oam/ietf#11]
2 use-cases for timestamps exist: 
(a) calculate delay: should be ns, 
(b) wall-clock time for audit purposes etc.

Changes: 2 timestamp options (short & wide):
1.	Short: 32 bit option: relative time
2.	Wide: 64 bit option: absolute time
Precision would be a per domain configurable option, i.e. th 32/64 bit fields are assumed to be their own namespace. Assumption is that relative time would be of ns accuracy for delay computation

**Comment by shwethab** [comment]
Or should the wide format be from draft-lapukhov-dataplane-probe-01:
Packet receive time is stored as 48-bits of seconds, 32-bits of nanoseconds, and
residence time is in 48-bits of nanoseconds.  
The length of this record is 128 bits.
`    0                   1                   2                   3
    0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |                    Receive Seconds [47:16]                    |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |    Receive Seconds [15:0]     |  Receive Nanoseconds [31:16]  |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |  Receive Nanoseconds [15:0]   |     Residence Time [47:32]    |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |                     Residence Time [31:0]                     |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+

`

**Comment by shwethab** [comment]
3.1.3. In-band OAM node data element format adds timestamp seconds, nanoseconds and transit delay nanoseconds. 


https://github.com/inband-oam/ietf/commit/6e30056794221bc0207614b345916ad908024fc1
