### ISSUE TITLE
Short and wide node-ID

### ISSUE THREAD

**Issue by brockners** [inband-oam/ietf#12]
A node ID of 24 bits appropriate for single domain, but might be considered too short for some inter-domain deployments.

Changes: Support 2 node ID options (short and wide):
1.	Short: 24 bit option
2.	Wide: 56 bit option
Choice would be per domain. Node ID has its own namespace, i.e. structure / allocation is domain specific.

**Comment by shwethab** [comment]
3.1.3.  In-band OAM node data element format: 
Hop_Lim and node_id:  4 octet field defined 
Hop_Lim and node_id:  8 octet field defined 

https://github.com/inband-oam/ietf/commit/6e30056794221bc0207614b345916ad908024fc1
