### ISSUE TITLE
IOAM VxLAN GPE: Header length clarification

### ISSUE THREAD

**Issue by shwethab** [inband-oam/ietf#129]
IOAM HDR len:  8-bit unsigned integer.  Length of the IOAM HDR in 4-octet units.

Can we change that last period to: 
"Length of the IOAM HDR in 4-octet units not including the first 4 octects." 

The first 4 octects are always present, so we don't need to count them.  

- Fabio Maino

**Comment by jalemon** [comment]
It would be consistent with other protocols such as Geneve. I vote yes.

**Comment by brockners** [comment]
Reflected in -02
