### ISSUE TITLE
Short and wide interface IDs

### ISSUE THREAD

**Issue by brockners** [inband-oam/ietf#13]
Interface ID: 16 bits appropriate for some, but potentially not for all deployments (e.g. broadband or mobile gateways have a large number of interfaces).

Changes: 2 interface ID options (short and wide):
1.	Short: 16 bit option
2.	Wide: 32 bit option
Choice would be per domain. Interface IDs (ingress/egress) have their own namespace, i.e. structure / allocation is domain specific.

**Comment by shwethab** [comment]
Added section 3.1.3.  In-band OAM node data element format with the following text.
   The In-band OAM node data elements are defined in 2 formats - short
   and wide that is selected by bit 7 in the OAM-trace-type field.  All
   the noda data elements MUST be 4-byte aligned in both the formats.
ingress_if_id and egress_if_id:  4 octet field defined as follows:
    0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |     ingress_if_id             |         egress_if_id          |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+

  ingress_if_id and egress_if_id:  8 octet field defined as follows:

    0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |                       ingress_if_id                           |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |                       egress_if_id                            |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+

https://github.com/inband-oam/ietf/commit/6e30056794221bc0207614b345916ad908024fc1
