### ISSUE TITLE
4-byte alignment

### ISSUE THREAD

**Issue by brockners** [inband-oam/ietf#14]
Make it explicit in the draft that all data records have to be 4 byte aligned.

**Comment by shwethab** [comment]
Added section 3.1.3.  In-band OAM node data element format with the following text.
   The In-band OAM node data elements are defined in 2 formats - short
   and wide that is selected by bit 7 in the OAM-trace-type field.  All
   the noda data elements MUST be 4-byte aligned in both the formats.

https://github.com/inband-oam/ietf/commit/6e30056794221bc0207614b345916ad908024fc1
