### ISSUE TITLE
draft-ietf-ippm-ioam-data-08 WGLC#1 comments: Nomenclature 

### ISSUE THREAD

**Issue by brockners** [inband-oam/ietf#150]
- [Greg Mirsky] Introduction section explains the "in-situ" term as “The term "in-situ" refers to the fact that the OAM data is added to the data packets rather than is being sent within packets specifically dedicated to OAM.” 
But with the introduction of Loopback and Direct Export as iOAM behaviors, iOAM data are not added to the data packet. And how these new iOAM functions affect the definition of IOAM control points in Section 3? 
_Suggested approach: Whatever name we choose, it might not capture all functionality accurately. The term IOAM has served us well so far. I suggest that we don’t change the name, but expand the description that IOAM as a name is motivated by the fact that a main use-case adds meta data to the packets in situ - but that there are other uses._

**Comment by inband-oam** [comment]
Introduction is expanded with the following text:
IOAM usecases and mechanisms have expanded as this document matured and have resulted in additional flags and options that may result in creation of additional packets dedicated to OAM. But the term IOAM continues to be used where "in-situ" refers to the OAM data added to the data packets that controls the content and additional OAM packet creation.
