### ISSUE TITLE
draft-ietf-ippm-ioam-data-08 WGLC#1 comments: Add further detail/clarifications to existing definitions

### ISSUE THREAD

**Issue by brockners** [inband-oam/ietf#152]
- [Greg Mirsky]  section 4.4 introduces the notion of an "iOAM capable node". Which of iOAM objects are expected to be supported by the iOAM capable node? If a node doesn't support a sub-set of iOAM data types, would it still be considered as iOAM capable? 
_Suggested approach: Detail what the minimal set of capabilities is that makes a node IOAM capable._ 

- [Greg Mirsky]  Section 4.4.1 I'm having a hard time figuring how the presence of Opaque State Snapshot space can be deduced. The explanation in NodeLen is not clear to me. 
_Suggested approach: For a node reading the IOAM data IOAM-Trace-Type bit 22 being set helps to deduce presence of opaque snap shot in node data.  For a node inserting IOAM data into the packet checking of IOAM-Trace-Type bit 22 followed by checking RemainingLen > (NodeLen + its opaque snapshot data len + 4) in 4 octet units._ 

- [Greg Mirsky]  The definitions of Bit 0 and Bit 8 of IOAM-Trace-Type differ only in part of the latter specifying that the format is wide. What is the length on data identified by Bit 0? 
_Suggested approach: Section 4.4.2. define individual field format, content, length. Bit 0 field is 4 octet long. Hop_Lim and node_id:  4-octet field defined as follows:_ 

 ~~~~
 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 
    
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ 
 |      Hop_Lim  |                 node_id                       | 
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ 
~~~~

- [Greg Mirsky]  Hop_limit in Section 4.4.2 is defined as “This is copied from the lower layer, e.g., TTL value in IPv4 header or hop limit field from IPv6 header of the packet when the packet is ready for transmission.”  What is the value of Hop_Limit field if the lower level does not include TTL/Hop Limit field? 
_Suggested approach: how about setting it to 0xffffffff when the lower level does not have a TTL/Hop limit equivalent field?_ 

- [Greg Mirsky]  What was the rationale to choose nanoseconds as the unit for transit delay? 
_Suggested approach: The routing/switching entities could be virtual switching packets across containers/VMs where the nanosecond delay makes sense, other than newer flavors of very fast switching silicon too._ 

- [Greg Mirsky]  How future proof is allocating four octets to express the length of an egress queue (queue depth)? What should be the value if an iOAM node cannot write the local value in four octets? 
_Suggested approach: mention that given that the unit isn’t defined – one can play with the unit * queue depth number)_ 

- [Greg Mirsky]  Similar to the questions above but in regard to the buffer occupancy field. 
_Suggested approach: see above_ 

- [Greg Mirsky]  Section 5 defers the specification of the particular timestamp format used in the given iOAM Namespace to the management plane. Does that mean that all nodes in the given iOAM Domain must support the same format? In other words, timestamps collected in the domain required to be in the homogeneous format - either all in NTP, all in PTP, or all in POSIX. That looks like unnecessary complexity and limitation and may cause lower accuracy of time measurement as an iOAM node may be required to transform from its native time format into the format chosen by the management plane. 
_Suggested approach: Use different namespaces if different formats are expected in the same domain_

**Comment by inband-oam** [comment]
[Greg Mirsky] section 4.4 introduces the notion of an "iOAM capable node". Which of iOAM objects are expected to be supported by the iOAM capable node? If a node doesn't support a sub-set of iOAM data types, would it still be considered as iOAM capable?
Suggested approach: Detail what the minimal set of capabilities is that makes a node IOAM capable.

iOAM capable node > replace to reflect node supporting IOAM functionality as defined by IOAM documents?

**Comment by inband-oam** [comment]
[Greg Mirsky] Section 4.4.1 I'm having a hard time figuring how the presence of Opaque State Snapshot space can be deduced. The explanation in NodeLen is not clear to me. https://github.com/inband-oam/ietf/pull/160 addresses this by clarifying the role of Trace type bit 22 being set/unset and how NodeLen has to be interpreted.

**Comment by inband-oam** [comment]
[Greg Mirsky] How future proof is allocating four octets to express the length of an egress queue (queue depth)? What should be the value if an iOAM node cannot write the local value in four octets?
Response: The unit for queue depth is not defined – one can play with the unit * queue depth number thus keeping it flexible to represent large values and hence is future proof.

[Greg Mirsky] Similar to the questions above but in regard to the buffer occupancy field.
Response: see above

[Greg Mirsky] Section 5 defers the specification of the particular timestamp format used in the given iOAM Namespace to the management plane. Does that mean that all nodes in the given iOAM Domain must support the same format? In other words, timestamps collected in the domain required to be in the homogeneous format - either all in NTP, all in PTP, or all in POSIX. That looks like unnecessary complexity and limitation and may cause lower accuracy of time measurement as an iOAM node may be required to transform from its native time format into the format chosen by the management plane.
Response: Use different namespaces if different formats are expected in the same domain
