### ISSUE TITLE
draft-ietf-ippm-ioam-data-08 WGLC#1 comments: Changes to existing definitions

### ISSUE THREAD

**Issue by brockners** [inband-oam/ietf#153]
- [Barak Gafni] Queue depth format – In order to align the standardization of units across the route, as done for time measurements for example, I would suggest to direct implementations towards reporting Bytes, rather than keeping it open for interpretation by the implementors. 
_Suggested approach: Per the discussion in the IOAM design team call on Feb/5 (see the minutes); Barak to provide suggested text_

**Comment by barakgafni** [comment]
This is the current description: 
The units of this field depend on the equipment type and deployment and has to be
              interpreted within the context of an IOAM-Namespace and/or
              node-id if used.

This is what the PR suggested:
The units of this field SHOULD follow the units used by the queue depth defnition

New suggestion:
The units of this field MAY be implementation specific. Hence, this units may need to be interpreted within the context of an IOAM-Namespace and/or node-id if used. The authors acknowledge that in some operational cases there is a need for the units to be consistent across a packet path through the network, hence recommend the implementations to enable support for a standard unit such as Bytes.

**Comment by brockners** [comment]
The suggested text sounds good to me. I'd suggest to change "to enable support for" to "to use".

**Comment by barakgafni** [comment]
Frank, sure, sounds good. Also, probably need to change MAY to may.
