### ISSUE TITLE
draft-ietf-ippm-ioam-data-08 WGLC#1 comments: Security related

### ISSUE THREAD

**Issue by brockners** [inband-oam/ietf#155]
- [Greg Mirsky]  Checksum Complement may be practical but it raises serious security issues. I couldn't find these being identified and discussed in the document. 
_Suggested approach: see Tal’s patch https://github.com/inband-oam/ietf/pull/146_

**Comment by talmi** [comment]
The Checksum Complement does not introduce any new security considerations. This is further discussed in the following response to the WG LC comments:
https://mailarchive.ietf.org/arch/msg/ippm/OEEPcOi1S0dPyocoO92vZ9weN44
