### ISSUE TITLE
draft-ietf-ippm-ioam-data-08 WGLC#1 comments: Editorial on Pre-allocated and Incremental Trace Options

### ISSUE THREAD

**Issue by brockners** [inband-oam/ietf#157]
- [Mickey Spiegel] Section 4.4.1 Pre-allocated and Incremental Trace Option-Types 
Text along the following lines should be added somewhere in this section: 
An IOAM transit node (that is not an IOAM encapsulating node or IOAM 
decapsulating node) MUST NOT modify any of the fields in the fixed size 
“trace option header”, other than “flags” and “RemainingLen”, i.e. an IOAM 
transit node MUST NOT modify the Namespace-ID, NodeLen, IOAM-Trace-Type, or 
Reserved fields. 
The “Reserved” field in Section 4.4.1 just says “Must be zero”. That should 
be expanded upon: 
An IOAM encapsulating node MUST set the value to zero upon transmission. 
IOAM transit nodes must ignore the received value. 
The “Node data List [n]” description is a little confusing, particularly 
the first sentence. 
Aside from the first sentence, the rest of this text, as well as the 
“RemainingLen” definition, imply that a “node data element” (i.e. list 
item) contains all of the IOAM-Data-Fields that a particular node adds to 
the trace option. 
This implies that the IOAM-Trace-Type bits (collectively) determine which 
data fields are included in each node data element. 
Any reference to the “n-th node data in the node data list” is misleading 
at best, more likely incorrect. That sentence should just be removed. 
The last sentence before the “IOAM-Trace-Type” bit definitions could be 
moved into the “Node data List [n]” definition instead: 
The order of packing the data fields in each node data element follows the 
bit order of the IOAM-Trace-Type field.
_Suggested approach: Follow Mickey's suggestions._

**Comment by inband-oam** [comment]
@mickeyspiegel for the Node data List [n] replacing the description with the following text:

This is a list of node data elements where the content of each node data element is determined by the IOAM-Trace-Type. The order of packing the data fields in each node data element follows the bit order of the IOAM-Trace-Type field. The last node data element in this list is the node data of the first IOAM capable node in the path. If the nth element of this list is populated by a node, the next IOAM capable node in the path populates (n-1)th element in this list. Populating the node data list in this way ensures that the order of node data list is the same for incremental and pre-allocated trace options. In the pre-allocated trace option, the index contained in RemainingLen identifies the offset for current active node data to be populated.
