### ISSUE TITLE
draft-ietf-ippm-ioam-data-08 WGLC#1 comments: Editorial DEX leftovers  

### ISSUE THREAD

**Issue by brockners** [inband-oam/ietf#159]
- [Mickey Spiegel] Section 8 Security Considerations 
There is text present about "immediate export" mode. 
This should probably be moved to the DEX draft. 
_Suggested approach: Remove from this draft, move to DEX draft._

- [Mickey Spiegel] Section 9 Acknowledgements 
There is text present about "immediate export" mode that should be removed. 
_Suggested approach: Remove associated acknowledgements. Move those to the DEX draft._

**Comment by talmi** [comment]
The first bullet was addressed in the security pull request:

https://github.com/inband-oam/ietf/pull/146

The second bullet is still valid.
