### ISSUE TITLE
draft-ietf-ippm-ioam-data-09 WGLC #2: Number of authors

### ISSUE THREAD

**Issue by brockners** [inband-oam/ietf#171]
[Martin Duke]  It's RFC Ed policy to have no more than 5 authors, and you have 12. Please follow these guidelines to trim the list down.

_Suggestion by the WG co-chair Tommy Pauly: 
To the authors:
Regarding the editorship of the document, I’d like to encourage everyone to see the editor/author split as really just a process and editorial concern, and not any reflection on the value of the various authors’ input. It’s a great thing we have so many people involved here!
If it’s helpful to have input from the chairs, I’d nominate that Shwetha and Frank be listed as editors, and we have a good section recognizing authors.
Thanks,
Tommy_

**Comment by shwethab** [comment]
Resolved
