### ISSUE TITLE
draft-ietf-ippm-ioam-data-09 WGLC #2: Check uppercase/lowercase normative language

### ISSUE THREAD

**Issue by brockners** [inband-oam/ietf#172]
[Martin Duke]  Throughout the document, there are many lower-case 'must', 'should', or 'may.' These should be reviewed, and most of them changed to upper-case. Non-upper-case should generally use synonyms like 'might' or 'could'.

**Comment by brockners** [comment]
…FB: We’ll review all the lower-case must/should/may statements once more and see whether there is a need to change to uppercase. My current understanding (please correct me if I’m wrong) was that per RFC 8174, the use of lower case must/may/should would be ok – we can of course see whether we can improve the wording to make sure things are not misread.

Suggested approach: In addition to the review, we'll try to reword lower-case must/should/may to other words to avoid any mis-readings.

**Comment by inband-oam** [comment]
try to replace lower should/may/must with something else where possible. Have capital should/may/must where required

**Comment by inband-oam** [comment]
Resolved
