### ISSUE TITLE
draft-ietf-ippm-ioam-data-09 WGLC #2: What happens if a node does not follow the normative requirements in section 4.4.1 (tracing)?

### ISSUE THREAD

**Issue by brockners** [inband-oam/ietf#174]
[Martin Duke]  Section 4.4.1 has many normative requirements for the options. What should transit nodes do if these are not followed (e.g. remainingLen is a garbage number)? Perhaps there should be an "error flag" in addition to the Overflow flag?

**Comment by brockners** [comment]
…FB: IMHO we can follow typical design principles here, i.e. be loose/tolerant on what you accept, strict on what you send. We can add a sentence that if a node receives a packet with IOAM data fields that it cannot decode/understand, it would simply ignore the IOAM data fields. Having a node figure out whether the IOAM data is really corrupted or not might be hard to achieve (e.g. it could be some future version that the node just does not understand).

**Comment by inband-oam** [comment]
check and confirm if there are fields/cases where such an error in processing is not already covered.

**Comment by inband-oam** [comment]
RemainingLen:  7-bit unsigned integer.  This field specifies the data
      space in multiples of 4-octets remaining for recording the node
      data, before the node data list is considered to have overflowed.
      Given that the sender knows the minimum path MTU, the sender MAY
      set the initial value of RemainingLen according to the number of
      node data bytes allowed before exceeding the MTU.

should this be updated? perhaps in issue 172?

**Comment by inband-oam** [comment]
Namespace identifiers allow devices which are IOAM capable to
   determine:

   o  whether IOAM-Option-Type(s) need to be processed by a device: If
      the Namespace-ID contained in a packet does not match any
      Namespace-ID the node is configured to operate on, then the node
      MUST NOT change the contents of the IOAM-Data-Fields.

   o  which IOAM-Option-Type needs to be processed/updated in case there
      are multiple IOAM-Option-Types present in the packet.  Multiple
      IOAM-Option-Types can be present in a packet in case of
      overlapping IOAM-Domains or in case of a layered IOAM deployment.

   o  whether IOAM-Option-Type(s) should be removed from the packet,
      e.g. at a domain edge or domain boundary.


clarify for IOAM-Option-Type that are unknown to the decap node.

What about transit nodes?

**Comment by shwethab** [comment]
Resolved

**Comment by shwethab** [comment]
@mickeyspiegel do you plan to address this before cutoff in about 24hrs?
