### ISSUE TITLE
draft-ietf-ippm-ioam-data-09 WGLC #2: Init values for node-list array?

### ISSUE THREAD

**Issue by brockners** [inband-oam/ietf#175]
[Martin Duke]  does the pre-allocated option have any sort of initial value the encapsulation node should set all the trace option data to? Would this allow the transit nodes to detect if there was a mistake in RemainingLen?

**Comment by brockners** [comment]
…FB: If we go with the above assumption, that nodes that do not understand the IOAM data fields would simply ignore them and leave the packet untouched, we would not benefit from any pre-set value on allocation. Depending on the implementation, pre-defined values may impose an additional burden on the encap node.

**Comment by inband-oam** [comment]
Closing the issue-> discussed in the design team meeting and agree with Frank's statement above. Initialized the value to a default does not bring any advantage.
