### ISSUE TITLE
draft-ietf-ippm-ioam-data-09 WGLC #2: IANA Considerations Registry Titles

### ISSUE THREAD

**Issue by brockners** [inband-oam/ietf#177]
[Al Morton] 7.  IANA Considerations
(apologies in advance for a long/recent/good experience with IANA, and the many other folks who try to help our friends at IANA)
This section appears to define a set of related registries.
The hierarchy could be named a bit more efficiently than:

7.1 In-Situ OAM Protocol Parameters Registry (IOAM) Protocol Parameters IANA registry

Suggest:
In-Situ OAM (IOAM) Protocol Parameters Group
7.1  IOAM Protocol Parameters Registry
     7.2  IOAM Option-Type Registry
     7.3  IOAM Trace-Type Registry

**Comment by shwethab** [comment]
Resolved
