### ISSUE TITLE
draft-ietf-ippm-ioam-data-09 WGLC #2: Manageability discussion

### ISSUE THREAD

**Issue by brockners** [inband-oam/ietf#179]
[Al Morton] Two Comments indicate the value of a Manageability Considerations section while resolving issues in the discussion. However, the -09 version still does not have this section a year later... The important topic discussed was congestion management, but there are no instances of "congest" in the -09 text.  (more, see below)

Section 3, Scope, etc. contains the topic:
Deployment domain (or scope) of in-situ OAM deployment:, in which many operational considerations are detailed that could be part of a Manageability Considerations: section.

**Comment by brockners** [comment]
…FB: Deployment and Manageability is a pretty wide topic. This is why we created a dedicated document for it:
https://tools.ietf.org/html/draft-brockners-opsawg-ioam-deployment-01. Are you ok if we continue to keep it as a dedicated document, or should we consider to replicate information from draft-brockners-opsawg-ioam-deployment into draft-ietf-ippm-ioam-data? Personally I’d prefer to avoid replication between documents.
[acm] 
Let’s avoid replication, as you suggest. An informative reference to the deployment draft WFM.
Also, I searched and did not find “congest” in the deployment draft, so it’s future work there.

**Comment by inband-oam** [comment]
Should we request for ops-directorate early review?

**Comment by inband-oam** [comment]
design team discussion: Add Manageability consideration and refer to deployment?

 congestion discussion is referring to flood of packets created with loopback flag or DEX -> both independent drafts now.

**Comment by shwethab** [comment]
Committed
