### ISSUE TITLE
Possible traces combinations 

### ISSUE THREAD

**Issue by davidmozes** [inband-oam/ietf#18]
Since we have about 8 bits of options ( 7 trace types and  1bit for long/short )  it gave about 128 combination.
I think we should state that control plan will decide on reenable amount of possible combination that need to be limited with upper limit 
On addition we should agree of format of not supported trace option (first  bit ,0Xff etc)

**Comment by shwethab** [comment]
Have done away with short/wide format bit and include node, interface and app wide with dedicated bits in trace-type.

Within an in-situ OAM domain possible combinations of these bits making the ioam-trace-type can be restricted by configuration knobs.

How about "If a node is updating its data record is not capable of populating the value of a field set int the iOAM-trace-type, the field value MUST be filled with zeroes."

**Comment by cpignata** [comment]
I don't like the "config knob" option since it really compounds operational complexity. I think that a concept of a domain wide policy is better and can be implemented various ways by a control plane (without hundreds of conf t).
The second part is good!

**Comment by davidmozes** [comment]
The problem is that Some time the middle box don't know how  to parse the new option .
so we have 2 cases : don't know /  not underspend the option  , know /understand but can't support . 
for the second option  I am OK 
for the first option we have to state that the control plan has to make sure that all the middle boxes understand the options

**Comment by brockners** [comment]
Given that IOAM is still a very new technology, it is close to impossible to decide right now which combinations of IOAM types are needed in deployments and which won't. Hence excluding combinations at the current point in time isn't feasible - as much as I understand the rationale behind it. 

For a particular domain, the set of options supported could of course be constrained. We should probably have a note in the draft for that. And if so, you of course want to drive the configuration consistently via a controller using Nectconf/YANG or similar (or even - longer term, embed things into a control protocol - but this control protocol will need to reach all nodes, i.e. embedding it into an IGP might not be that feasible).

I'm also ok with specifying that if a node is IOAM capable but cannot perform a particular action should fill fields with zeros (assuming that it is at least capable of filling the zeros in - might be challenging)...
So probably something like: "The IOAM encapsulating node MUST initialized data records that it adds to the packet to zero"; "If a node which is supposed to update an IOAM data record is not capable of populating the value of a field set in the iOAM-trace-type, the field value MUST be left unaltered (i.e. stay with all zeros)."

**Comment by shwethab** [comment]
Section 3.1.4 updated to:
 The IOAM encapsulating node MUST initialize data records that it adds to the packet to zero.  If a node which is supposed to update an IOAM data record is not capable of populating the value of a field set in the iOAM-trace-type, the field value MUST be left unaltered except when  explicitly specified in the field description below. In the description of  data record field below if zero is valid value then a non-zero value to mean not populated is specified.

Added this for ingress/egress interface ids, timestamp nanoseconds, transit delay, queue depth: 
When this field is part of the data record but a node populating the record is not able to fill it, the field position in the record must be filled with value 0xFFFF to mean not populated.
