### ISSUE TITLE
Hop  limit Should be defined from where it is taken (In the ingress , after the router? ) 

### ISSUE THREAD

**Issue by davidmozes** [inband-oam/ietf#19]
Hop_Lim:" 1-octet unsigned integer. It is set to the Hop Limit
value in the packet at the node that records this data. Hop
Limit information is used to identify the location of the node
in the communication path. This is copied from the lower layer
for e.g. TTL value in IPv4 header or hop limit field from IPv6
header of the packet"

Should be defined from where it is taken (In the ingress , after the router )

**Comment by shwethab** [comment]
1-octet unsigned integer. It is set to the Hop Limit value in the packet at the node that records this data. Hop Limit information is used to identify the location of the node in the communication path. This is copied from the lower layer for e.g. TTL value in IPv4 header or hop limit field from IPv6 header of the packet _**when the packet is ready for transmission.**_
