### ISSUE TITLE
4)	Pre-allocated Trace Option  overflow bit 

### ISSUE THREAD

**Issue by davidmozes** [inband-oam/ietf#20]
Pre-allocated Trace Option 
a)	We need to have the over flow bit as well the same as in the incremental

**Comment by shwethab** [comment]
Overflow bit will not be accurate. Think of this scenario: A node has a opaque snapshot that wont fit into preallocated space. But a subsequent node may have sufficient space for the data it wants to populate. setting overflow here wont be useful. 
 Have added it anyway in -03..
