### ISSUE TITLE
Data draft - Namespace-ID value 0x0000

### ISSUE THREAD

**Issue by talmi** [inband-oam/ietf#203]
Comment from Martin Duke:

(5.3 and many other places): "The Namespace-ID value of 0x0000 is default and

   known to all the nodes implementing IOAM."

 

This is repeated several times and I'm not sure what it means. Does it mean all nodes MUST be nodes in this namespace? Is there a default group of settings for this namespace that I missed?  Does it mean that if there is one config, it must use 0x0000?

**Comment by brockners** [comment]
The use of "Default Namespace-ID" is indeed not specified clearly. Let's summarize the needs:

1) We need a namespace-id which every IOAM node in the absence of the definition of a specific namespace-id COULD use.
2) We need a namespace-id that every IOAM node in the absence of the definition of a specific namespace-id SHOULD look at. 
3) We need a value for the namespace-id that says "no specific namespace-id has been defined". 

The default namespace-id of 0x0 could cover all the three cases.
Suggested text, replacing the old "The Namespace-ID value of 0x0000 is default and known to all the nodes implementing IOAM" (and similar occurrences) :

NEW: 
The Namespace-ID value of 0x0000 is the "Default-Namespace-ID". 
The Default-Namespace-ID indicates that no specific namespace is associated with the IOAM data fields in the packet. 
The Default-Namespace-ID MUST be supported by all nodes implementing IOAM.
A use-case for the Default-Namespace-ID are deployments which do not leverage specific namespaces for some or all of their packets that carry IOAM data fields.

**Comment by talmi** [comment]
Updated in version 11.
