### ISSUE TITLE
Pre-allocated Trace Option  index is not relevnat any more 

### ISSUE THREAD

**Issue by davidmozes** [inband-oam/ietf#21]
It stated in the draft : “The index 
 contained in "Elements-left" identifies the current active Node
data to be populated.” 
This is not clear after we add the user defined option . Should be the pointer in bytes  for the last place the active node should be write into

**Comment by shwethab** [comment]
s/Elements-left/Bytes-left
updated in -03

**Comment by cpignata** [comment]
Sorry this is a small nit, but... Could we :s/byte/octet/g because strictly a byte is machine dependent but octet is always 8 bits. I would do that but I'm on my phone without computer.
