### ISSUE TITLE
ioam acronym

### ISSUE THREAD

**Issue by talmi** [inband-oam/ietf#29]
Throughout the four drafts iOAM is used with a lowercase 'i'. In some presentations IOAM with an uppercase 'I' was used. What is the correct form?
Let's be consistent and let's add it to the acronym list at the beginning of each document.

**Comment by brockners** [comment]
How about "IOAM" - because this was used for the draft WG discussions and several folks started to adopt it.

**Comment by brockners** [comment]
Fixed in the latest rev of -03: https://github.com/inband-oam/ietf/commit/d7d4f22ca9124a38980dc4f4f424ccf5830cd569
