### ISSUE TITLE
Bit order

### ISSUE THREAD

**Issue by talmi** [inband-oam/ietf#30]
In draft-brockners-inband-oam-data:

In most of the document (an in general in IETF documents) bit 0 is the most significant bit. So we should align this accordingly, right?

<t hangText="Bit 0">"Overflow" (O-bit) (least significant bit)

**Comment by brockners** [comment]
Fixed in recent -03 revision - see commit: https://github.com/inband-oam/ietf/commit/01d1aa177b1c763242a4ddab9cf2df41efc78ffa
