### ISSUE TITLE
Loopback

### ISSUE THREAD

**Issue by talmi** [inband-oam/ietf#31]
Loopback mode needs more text:

- The looped-back traffic is not in-situ anymore... It is 'just' OAM.
- The assumption is that there is a reverse path, and that the transit node needs to change the packet in the 'transport' layer to be sent through the reverse path.
- On its way back to the encapsulating node, the packet is processed by transit nodes like a regular iOAM, right?
- On its way back the looped back packet may include a larger number of data elements than the maximum (the number of hops on an almost-round-trip is twice as many hops).
- Whether we expect the loopback bit is set in all packets or only in a fraction of them.

**Comment by brockners** [comment]
Fixed in recent -03 revision - see commit: https://github.com/inband-oam/ietf/commit/01d1aa177b1c763242a4ddab9cf2df41efc78ffa
