### ISSUE TITLE
OAM Type

### ISSUE THREAD

**Issue by talmi** [inband-oam/ietf#32]
In draft-brockners-inband-oam-data:

I believe this is a typo, right? Suggest fix below.

OLD:
<t hangText="Node data List [n]:">Variable-length field. The
              format of which is determined by the OAM Type representing the
              n-th Node data in the Node data List.

NEW:
<t hangText="Node data List [n]:">Variable-length field. The
              format of which is determined by the  iOAM Trace Type.

**Comment by brockners** [comment]
Typo indeed. Needs fixing per your suggestion

**Comment by brockners** [comment]
Fixed in recent -03 revision - see commit: https://github.com/inband-oam/ietf/commit/01d1aa177b1c763242a4ddab9cf2df41efc78ffa
