### ISSUE TITLE
Error value - zeros?

### ISSUE THREAD

**Issue by talmi** [inband-oam/ietf#33]
In draft-brockners-inband-oam-data:

The draft says that:

If a node is
          updating its data record is not capable of populating the value of a
          field set in the iOAM-trace-type, the field value MUST be filled
          with zeroes.

However, what if the real value of the field is zero? The timestamp nanoseconds / the ingress_if_id and egress_if_id / the queue depth may indeed be zero.
How about a value of all 1's to denote an error?

**Comment by shwethab** [comment]
Perhaps have a different N/A values for different fields..
Atleast there is opaque snapshot field that has length and schema id cannot be all 1st

**Comment by shwethab** [comment]
Section 3.1.4 updated to:
The IOAM encapsulating node MUST initialize data records that it adds to the packet to zero. If a node which is supposed to update an IOAM data record is not capable of populating the value of a field set in the iOAM-trace-type, the field value MUST be left unaltered except when explicitly specified in the field description below. In the description of data record field below if zero is valid value then a non-zero value to mean not populated is specified.

Added this for ingress/egress interface ids, timestamp nanoseconds, transit delay, queue depth:
When this field is part of the data record but a node populating the record is not able to fill it, the field position in the record must be filled with value 0xFFFF to mean not populated.
