### ISSUE TITLE
Queue Depth Units

### ISSUE THREAD

**Issue by talmi** [inband-oam/ietf#34]
In draft-brockners-inband-oam-data:

The units of the field <queue depth> should be defined.
I suggest to add the sentence:

The queue depth field specifies the number of buffers in the queue.

**Comment by brockners** [comment]
Implemented in -03 version. See https://github.com/inband-oam/ietf/commit/c17afadf866b20601d9ca7ab5ea10ef3eb3d19bb

**Comment by brockners** [comment]
Implemented in -03 version. See https://github.com/inband-oam/ietf/commit/c17afadf866b20601d9ca7ab5ea10ef3eb3d19bb
