### ISSUE TITLE
TLV format and Option format

### ISSUE THREAD

**Issue by talmi** [inband-oam/ietf#35]
The TLV format needs clarifying in the document. 

      In-situ OAM data is
      defined as options in Type-Length-Value (TLV) format. The TLV format for
      each of the three different types of in-situ OAM data is defined in this
      document.

The text mentions a TLV format, but I haven't found a place in the document that actually defines a TLV format. The 'three types' are not completely clear either.

More specifically, it is not clear where in the packet the POT option resides, and where the E2E option resides. We should probably add a figure that specifies the packet format of a packet that includes trace information, POT, and E2E.

**Comment by shwethab** [comment]
The text needs rework to clarify how the option header and value will fit into transport specific TLV format.. but a packet format will be better specified in transport draft?

**Comment by brockners** [comment]
Updated the data-records draft to reflect the fact that we're not really defining TLVs but fixed length records which get selected through a bit field.

https://github.com/inband-oam/ietf/commit/b0a849735f2a1b78cfe4ea95153a3d10d7cd1535
