### ISSUE TITLE
not valid telemetry

### ISSUE THREAD

**Issue by davidmozes** [inband-oam/ietf#39]
According to spec, see below.

queue depth: 4-octet unsigned integer field. This field indicates
the current length of the egress interface queue of the interface
from where the packet is forwarded out. The queue depth is
expressed as the current number of memory buffers used by the
queue (a packet may consume one or more memory buffers, depending
on its size). When this field is part of the data field but a
node populating the field is not able to fill it, the field
position in the field must be filled with value 0xFFFF to mean not
populated.

should be  0xFFFFFFFF (32 bits of 1) and not 0xFFFF (16 bits of 1)
I think it is a typo and means 32 bits of 1. Please ack.

**Comment by brockners** [comment]
This is a bug/typo indeed. Fixed in -05 version of the draft.
