### ISSUE TITLE
Transport draft: nsh - instead of NSH type 2 metadata TLVs, use Next Protocol in the NSH Base Header

### ISSUE THREAD

**Issue by mickeyspiegel** [inband-oam/ietf#44]
Rather than using NSH Type 2 metadata TLVs, encapsulating iOAM in NSH, use an encapsulation of iOAM over NSH, allocating new values for Next Protocol in the NSH Base Header. This would be similar to the approach taken for VXLAN-GPE and GRE. In order to make iOAM transport encapsulations more hardware friendly, whenever possible prefer encaps of iOAM over another protocol rather than in another protocol, especially when that protocol uses nested TLVs internally.

**Comment by mickeyspiegel** [comment]
Another reason to change the proposed NSH encapsulation is that the length of each NSH MD Type 2 Optional Variable Length Metadata is limited to 127 octets, which will be too small for many deployments.

**Comment by inband-oam** [comment]
11f9f30c28dae3a99a53a8a0c26997f513e75c91 addresses this.
