### ISSUE TITLE
"Maximum Length" / "Octets-left" fields in IOAM Trace Options are too small

### ISSUE THREAD

**Issue by mickeyspiegel** [inband-oam/ietf#45]
8-bits in octets gives a max of 255 octets, or 63 node data fields. If all (wide where possible) IOAM-Trace-Type bits are set, each node adds 40 octets plus the size of the variable length Opaque State Snapshot. This seems too tight.

One possibility for increasing the size is to use multiples of 4-octets rather than just octets.

**Comment by mickeyspiegel** [comment]
If these fields are to be expanded, then the length in the IOAM transport header just above the IOAM Trace Option must also be expanded. Looking at draft-brockners-inband-oam-transport-04 (in progress):

- IPv6 hop by hop extensions are limited to 255 octets.
- The IOAM Trace Header after GRE includes a reserved octet just before the "IOAM HDR Len", so "IOAM HDR Len" can be extended beyond 8 bits.
- The IOAM Trace Header after VXLAN-GPE includes a "Type" octet just before the "IOAM HDR Len". The "Type" octet can be reduced in size or removed (why does the VXLAN-GPE encoding have a "Type" octet but the GRE header does not? Is it redundant with the VXLAN-GPE "Next Protocol"?) so that the "IOAM HDR Len" can be extended beyond 8 bits.
- The entire NSH header is limited to 252 octets, and each NSH MD Type 2 Optional Variable Length Metadata is limited to 127 octets. This is another reason to change the NSH encoding to a format similar to IOAM over VXLAN-GEP and IOAM over GRE.

**Comment by inband-oam** [comment]
11f9f30c28dae3a99a53a8a0c26997f513e75c91 addresses this
