### ISSUE TITLE
Add "Node Data Length" to IOAM Trace Header

### ISSUE THREAD

**Issue by mickeyspiegel** [inband-oam/ietf#46]
This field specifies the length of data added by each node in multiples of 4-octets.  For example, if 3 IOAM-Trace-Type bits are set and none of them is wide, then the Node Data Length would be 3.  If 3 IOAM-Trace-Type bits are set and 2 of them are wide, then the Node Data Length would be 5.

There are several possibilities for where to put this field:
1. Squeeze the IOAM Trace Header by specifying Maximum Length as 7-bits in multiples of 4-octets, add 4-bits of Node Data Length, and squeeze flags down to 5 bits.
2. Increase the size of the fixed part of the IOAM Trace Header to 8 octets.
3. Use a reserved field in the IOAM Transport Header just before the IOAM Trace Header.

**Comment by mickeyspiegel** [comment]
Proposed details for option 1:

   In-situ OAM Pre-allocated Trace Option header:

<pre>
    0                   1                   2                   3
    0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |         IOAM-Trace-Type       |NodeLen|  Flags  | Octets-left |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
</pre>

   In-situ OAM Incremental Trace Option Header:

<pre>
    0                   1                   2                   3
    0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |        IOAM-Trace-Type        |NodeLen|  Flags  | Max Length  |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
</pre>

<pre>
   Octets-left:  8-bit unsigned integer.  It is the data space in multiples of
      4-octets remaining for recording the node data.  This is used as an
      offset in data space to record the node data element.

   Maximum Length:  7-bit unsigned integer.  This field specifies the
      maximum length of the node data list in multiples of 4-octets.
      Given that the sender knows the minimum path MTU, the sender can
      set the maximum length according to the number of node data bytes
      allowed before exceeding the MTU.  Thus, a simple comparison
      between "Opt data Len" and "Max Length" allows to decide whether
      or not data could be added.

   Node Data Length: 4-bit unsigned integer.  This field specifies the
      length of data added by each node in multiples of 4-octets.  For
      example, if 3 IOAM-Trace-Type bits are set and none of them is
      wide, then the Node Data Length would be 3.  If 3 IOAM-Trace-Type
      bits are set and 2 of them are wide, then the Node Data Length
      would be 5.

   Flags  5-bit field.  Following flags are defined:
   ...
</pre>

**Comment by mickeyspiegel** [comment]
Proposed details for option 2:

In-situ OAM Pre-allocated Trace Option header:

<pre>
    0                   1                   2                   3
    0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |                IOAM-Trace-Type                |    Reserved   |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |     Flags     | Node Data Len |          Octets-left          |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
</pre>

In-situ OAM Incremental Trace Option Header:

<pre>
    0                   1                   2                   3
    0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |                IOAM-Trace-Type                |    Reserved   |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |     Flags     | Node Data Len |         Maximum Length        |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
</pre>

<pre>
   Octets-left:  16-bit unsigned integer.  It is the data space in octets
      remaining for recording the node data.  This is used as an offset
      in octets in data space to record node data element.

   Maximum Length:  16-bit unsigned integer.  This field specifies the
      maximum length of the node data list in octets.  Given that the
      sender knows the minimum path MTU, the sender can set the maximum
      of node data bytes allowed before exceeding the MTU.  Thus, a
      simple comparison between "Opt data Len" and "Max Length" allows
      to decide whether or not data could be added.

   Node Data Length: 8-bit unsigned integer.  This field specifies the
      length of data added by each node in octets.  For example, if 3
      IOAM-Trace-Type bits are set and none of them is wide, then the
      Node Data Length would be 12.  If 3 IOAM-Trace-Type bits are set
      and 2 of them are wide, then the Node Data Length would be 20.

   Flags  8-bit field.  Following flags are defined:
</pre>

**Comment by inband-oam** [comment]
11f9f30c28dae3a99a53a8a0c26997f513e75c91 addresses this, option 1 is chosen.
