### ISSUE TITLE
IOAM-Trace-Type bit order

### ISSUE THREAD

**Issue by avivkfir** [inband-oam/ietf#51]
On 4.1.1.  Pre-allocated Trace Option:
IOAM-Trace-Type.bit[0] is defined as (Most significant bit).
Also documented in 4.1.2.

The examples in 4.1.4.  Examples of IOAM node data, are not consistent with that.
See below example
0x002B:  IOAM-Trace-Type is 0x2B then the format of node data is:

        0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
       +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
       |   Hop_Lim     |              node_id                          |
       +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
       |     ingress_if_id             |         egress_if_id          |
       +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
       |                  timestamp nanoseconds                        |
       +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
       |                            app_data                           |
       +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+

**Comment by shwethab** [comment]
Changing the Bit 0 to least significant bit.
