### ISSUE TITLE
draft-brockners-inband-oam-data -01 feedback

### ISSUE THREAD

**Issue by inband-oam** [inband-oam/ietf#7]
Jen Linkova:
1)
"In-band OAM data is added to a packet on entering the in-band
OAM-domain and is removed from the packet when exiting the domain. " -
it might be just me but I found the terminology a bit confusing. When
I read it for the first time I assumed that "data" means "data in OAM
header. While it looks like by "data" you mean "the data container".
Shall the container and the data be called differently?

2) IMHO calling a node "in-band OAM encapsulating" is a bit confusing
as at least for some cases there is no encapsulation. Maybe smth like
'pop/push' MPLS terminology? Or would it confuse people even more?

3) (sorry for nitpicking)
"Hop_Lim:  1 octet Hop limit that is set to the TTL value in the
packet at the node that records this data."
s/TTL/TTL or Hop Limit/ - that field is called Hop Limit in IPv6, not TTL.

Deepak Kumar:
I believe just I-oam header should be placed flexibly, if network is l2/l3 leaf and traffic is within one data center then current format is fine.
If traffic is going over L2 and L3 vxlan seperated, or Border Leaf, Data Center Interconnect I-oam header can come fixed byte inside data and configuration policy can determine this behavior if required.
Now How to indicate if common OAM header is starting immediately or after Fixed byte, I will left to community. 
Using single "O" bit is also fine for active OAM as we can look at two places if we use optional Fixed byte.
As I-OAM is for real data it will be issue and they might not support that mode or getting extra bit in Datapath header will solve this issue.
L2/L3 distributed scenario is currently deployed by operator.
   In-band OAM header in VXLAN GPE header:
 
  ```
 In-band OAM header in VXLAN GPE header:
 
    0                   1                   2                   3
    0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |                    Outer Ethernet Header                      |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |                        Outer IP Header                        |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |                       Outer UDP Header                        |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ +
   |R|R|Ver|I|P|R|O|          Reserved             | NP = i.b.OAM  |  |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ GPE
   |     Virtual Network Identifier (VNI)          | Reserved      |  |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ +
            Fixed Byte of Inner Packet Real Data (Optional)
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ +
   | Type =i.b.OAM | i.b.OAM HDR len |  Reserved     | NP = IP/Eth |  |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+iOAM
   |                     in-band OAM options                       |  |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ +
   |                                                               |
   |                                                               |
   |                     Payload + Padding (L2/L3/ESP/...)         |
   |                                                               |
   |                                                               |
   |                                                               |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
```

Tal:

OLD:
 
      Bit 0    When set indicates presence of node_id in the Node data.
 
      Bit 1    When set indicates presence of ingress_if_id in the Node
               data.
 
      Bit 2    When set indicates presence of egress_if_id in the Node
               data.
 
      Bit 3    When set indicates presence of timestamp in the Node
               data.
 
      Bit 4    When set indicates presence of app_data in the Node data.
 
      Bit 5-7  Undefined in this document.
 
NEW:
 
      Bit 0    When set indicates presence of Hop_Lim and node_id in the Node data.
 
      Bit 1    When set indicates presence of ingress_if_id and egress_if_id in the Node
               data.
 
      Bit 2    When set indicates presence of short timestamp data.
 
      Bit 3    When set indicates presence of long timestamp in the Node
               data.
 
      Bit 4    When set indicates presence of app_data in the Node data.
 
      Bit 5-7  Undefined in this document.
 
 
OLD:
   timestamp:  4 octet timestamp when packet has been processed by the node.
 
 
NEW:
   short timestamp:  a 4-octet timestamp that specifies the time at which the packet was received by the node. [TBD] Need to specify the semantics of this field.
 
   long timestamp: an 8-octet timestamp that specifies the time at which the packet was received by the node. The format of this field is identical to the 64 least significant bits of the IEEE 1588-2008 Precision Time Protocol timestamp format [IEEE1588v2]. This truncated format consists of a 32-bit seconds field followed by a 32-bit nanoseconds field. As defined in [IEEE1588v2], the timestamp specifies the number of seconds elapsed since 1 January 1970 00:00:00 according to the International Atomic Time (TAI).

**Comment by shwethab** [comment]
Addressed in : https://github.com/inband-oam/ietf/commit/6e30056794221bc0207614b345916ad908024fc1
