### ISSUE TITLE
draft-brockners-inband-oam-transport-01 feedback

### ISSUE THREAD

**Issue by inband-oam** [inband-oam/ietf#8]
Jen Linkova
0) "n=max number of nodes to be allocated"
Shall it be "maximum number of nodes updating OAM data"?
BTW I can not see 'n' used in the formulas later...

1)
"Based on PMTU advertised in the domain" - I do not think PMTU is
advertized. MTU on a given link might be advertized somehow.
But end2end PMTU is not advertized. Probably it should be re-phrased
like 'calculated based on the packet size and the minimal MTU on all
links within the OAM domain'

2) "Let k = number of node data that can be allocated by this node" -
IMHO "number of node data" sounds a bit confusing...at elast to me,
but it might be just me...

3) Procedures to insert/update IPv6 headers keep referring to
Segments_Left field, while there is no such field in HbH header. Such
field does exist in Routing Header, but not in HbH.
In addition to that, in all those procedures one more step needs to be
added: modifying "next header" value in the basic IPv6 header and in
HbH header (after it is inserted).

Hemant Singh:
It's good you have configuration on ingress and egress nodes to add/strip the EH.  Maybe add some text to say if the original packet is close to 1280 bytes in size (MTU for IPv6 on Ethernet) an OAM EH can't be added and an error is reported.   Likewise if an ICMPv6 forwarding error occurs between ingress and egress routers, the router generating the ICMPv6 error should strip the OAM EH before sending the ICMPv6 message to the source.   See if any other failure conditions makes sense to document in your draft.

**Comment by brockners** [comment]
Feedback accomodated in -02 version of the transport draft
