### ISSUE TITLE
draft-brockners-proof-of-transit-01 feedback

### ISSUE THREAD

**Issue by inband-oam** [inband-oam/ietf#9]
Tal Mizrahi [mailto:talmi@marvell.com]
To summarize my take on this thread:
The proposed mechanism has two significant vulnerabilities that (in my understanding) are currently not addressed:
1.       A man-in-the-middle can replace the POT of packet A with the POT of packet B.
2.       It is possible to replay POTs within a certain time window, whose length is determined by the timestamp resolution.
 
Add threat model
List out the threats that are addressed by this mechanism

**Comment by sashank** [comment]
We have addressed this issue in the current commit, hence closing this
